### PR TITLE
Added MTable plugin.

### PR DESCRIPTION
**Pull request by icefoxen**
This is maybe less useful now than when I originally wrote it, but I'll submit it anyway:

This plugin adds a new table syntax that I find less irritating than having to hand-align everything.  Example:

``````
``` {.mtable}
| some | table |
| that doesn't have the columns | aligned with each other |
```
``````

is equivalent to:

```
--------------------------------  ------------------------
some                              table
that does have the columns        aligned with each other
--------------------------------  ------------------------
```

This is similar to Pandoc's pipe_tables extension but not all versions of pandoc have that (particularly the one in Debian 7 stable), so this hack might be useful to someone.

### CODE REVIEW

**Comment by icefoxen** [comment]
Added a bunch of other fixes.

**Comment by jgm** [comment]
It would be much more useful to have separate PRs for separate issues, rather than a whole bunch of unrelated changes all in one pile.

**Comment by icefoxen** [comment]
As annoying as it is to play git-surgery, you are right.

**Comment by jgm** [comment]
Thanks for doing that.

**Comment by icefoxen** [comment]
No problemo.  Thanks for still being around to accept merge requests.  :heart:

**Pull request closed without merging**
