### PR TITLE
Add Ext_emoji to readerExtensions

### PR DESCRIPTION
**Pull request by conal**
A small change to enable emoji.

### CODE REVIEW

**Comment by jgm** [comment]
Did you mean to enable emojis only when lhs is enabled?  It's not clear why those should be connected.

**Comment by conal** [comment]
Oops! Thanks for the skeptical eye, John!

**Comment by conal** [comment]
Hm. The build error appears to be independent of my PR.

**Comment by jgm** [comment]
OK, thanks!

**Pull request merged**
