### PR TITLE
Fixed Build for Pandoc 1.16 on GHC 7.8.4

### PR DESCRIPTION
**Pull request by cleichner**

### CODE REVIEW

**Comment by jgm** [comment]
There are three separate commits here.
Only one fixes a typo.

**Comment by cleichner** [comment]
Is this better or would you like it split into multiple pull requests?

**Comment by jgm** [comment]
If there are logically separate changes, it would be best
to have multiple PRs that can be considered individually.

+++ Chas [Jan 15 16 14:22 ]:

**Review by rybak — COMMENTED** [review]
With `Export.hs` having been deleted in eed32638f4f6e3b2f4b8a9a04c4b72001acf9ad8, this PR is obsolete.

**Pull request closed without merging**
