### PR TITLE
Revert accidental change of singlequotes from UTF-8 to ascii.

### PR DESCRIPTION
**Pull request by wouteroostervld**
Blame:

d98c60cc Network/Gitit/Initialize.hs (Caleb McDaniel  2014-08-13 16:55:47 -0500 174)

### CODE REVIEW

**Comment by homeworkprod** [comment]
Care to elaborate? I fail to understand why a single quote should be used in a place where an apostrophe belongs. Those are different characters with different meanings/uses.

**Comment by wouteroostervld** [comment]
homeworkprod: See d98c60c Network/Gitit/Initialize.hs . An UTF-8 ' is replaced in this diff by an ascii '. This breaks the link to the guide on the homepage.

**Comment by jgm** [comment]
Thanks!

**Comment by homeworkprod** [comment]
@wouteroostervld, I do see the difference between those two characters, and that you have reverted the previous change.

My question is: Don't apostrophes work in Gitit links?

Because changing the link (and its label) to using an apostrophe is the right thing, IMHO; a single quote is orthographically wrong, AFAIK.

So as I see it, the right think to do here is to keep the page name writting with an apostrophe, and make the link work, and *not* changing it to the wrong character. If stuff breaks, than the bug is somewhere else, I'd say.

**Comment by wcaleb** [comment]
I accept the "blame." ;-) Thanks @wouteroostervld.

**Comment by jgm** [comment]
See http://practicaltypography.com/apostrophes.html

The current character (same as right single quote) is
typographically correct.  Straight quotes should not be used
for apostrophes.  So there is no problem that I can see with
@wouteroostervld's fix.

+++ Jochen Kupperschmidt [Aug 24 15 11:23 ]:

**Comment by homeworkprod** [comment]
@jgm, thanks, I was indeed mistaken.

For the record: The *typographically correct* character is `U+2019` (labeled "RIGHT SINGLE QUOTATION MARK" in Unicode) whereas the "typewriter apostrophe" (`U+0027`) is a highly overloaded replacement character for various symbols.

Interestingly, Latin-1/ISO-8859-1 and Latin-9/ISO-8859-15 do not contain the typographically correct character (according to Wikipedia).

**Pull request merged**
